// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcdzk1JaOb4FqUrqbzLeWX3uT1KWjIN5s',
    appId: '1:844436692852:web:988cfe0161d798bf051621',
    messagingSenderId: '844436692852',
    projectId: 'video-app-906db',
    authDomain: 'video-app-906db.firebaseapp.com',
    storageBucket: 'video-app-906db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_C-MyswKkzqz2vBrggoABmloWGFl-pc',
    appId: '1:844436692852:android:05631fac64dc904d051621',
    messagingSenderId: '844436692852',
    projectId: 'video-app-906db',
    storageBucket: 'video-app-906db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChCzrr4vdBtz3Hg30B2cNdtO3-Nb-6CNw',
    appId: '1:844436692852:ios:7812f5a9a01cee40051621',
    messagingSenderId: '844436692852',
    projectId: 'video-app-906db',
    storageBucket: 'video-app-906db.appspot.com',
    iosBundleId: 'com.example.videoStreamingApp',
  );
}
